version: '2'
###
services:
  #_____________________________________________________
  #
  base.gateway:
    environment:
      - SSL_CERT=/opt/base/gateway/conf.d/cert/www.cubbles.world.ssl.crt
      - SSL_CERT_KEY=/opt/base/gateway/conf.d/cert/www.cubbles.world.ssl.key
      - BASE_AUTH_SECRET=cNa081#nulB3!
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/www.cubbles.world/cert:/opt/base/gateway/conf.d/cert:ro
  #_____________________________________________________
  #
  base.authentication:

  #_____________________________________________________
  #
  base.userprofilemanagement:

  #_____________________________________________________
  #
  base.coredatastore:
    ports:
      - "5984:5984"
    volumes:
      - /mnt/sda1/tmp:/var/backups

#========================================================
# volumes
# volumes:

#
#========================================================
## networks
# networks: