version: '2'
###
services:
  #_____________________________________________________
  #
  base.gateway:
    environment:
      - NODEMON_OPTIONS=-L -e conf,locations,ssl --watch /opt/gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/sda1/projects.webbles/github/base.gateway/opt/gateway:/opt/gateway:rw

  #_____________________________________________________
  #
  base.authentication:
    environment:
      - NODEMON_OPTIONS=-L --watch /opt/authentication/base-authentication-service/authentication-service.js --watch /opt/authentication/base-authentication-service/lib
    volumes:
      - /mnt/sda1/projects.webbles/git/base/authentication/base-authentication-service:/opt/authentication/base-authentication-service:ro
  #_____________________________________________________
  #
  base.userprofilemanagement:
    environment:
      - NODEMON_OPTIONS=-L --watch /opt/userprofilemanagement/base-userprofilemanagement-service/service.js --watch /opt/userprofilemanagement/base-userprofilemanagement-service/lib
  #_____________________________________________________
  #
  base.coredatastore:
    ports:
      - 5984:5984
    volumes:
      - /mnt/sda1/tmp:/backups

#========================================================
# volumes
# volumes:

#
#========================================================
## networks
#networks:
#  devbase:
#    external: false